CREATE TABLE ANUNCIANTE (
    ID INT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    CPFCNPJ VARCHAR(14) NOT NULL,
    TELEFONE VARCHAR(15),
    TIPO_LOCALIZACAO VARCHAR(1) NOT NULL DEFAULT 'U' COMMENT 'U = Urbana, R = Rural',
    ENDERECO VARCHAR(100) NOT NULL,
    NUMERO_ENDERECO VARCHAR(10),
    COMPLEMENTO VARCHAR(100),
    CEP VARCHAR(9),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    PAIS VARCHAR(2) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    SALDO INT DEFAULT 0,
    PRIMARY KEY (ID)
);

CREATE TABLE TIPO_ANUNCIO (
    ID INT NOT NULL AUTO_INCREMENT,
    CATEGORIA VARCHAR(1) NOT NULL COMMENT 'B = Bronze, P = Prata, O = Ouro',
    VALOR INT NOT NULL,
    DURACAO_DIA INT NOT NULL,
    PRIMARY KEY (ID)
);

CREATE TABLE IMOVEL (
    ID INT NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(150) NOT NULL,
    OBSERVACAO TEXT,
    TIPO_IMOVEL VARCHAR(1) NOT NULL COMMENT 'C = Casa, A = Apartamento, L = Lote',
    TIPO_NEGOCIO VARCHAR(1) NOT NULL COMMENT 'A = Aluguel, V = Venda, T = Troca',
    VALOR DECIMAL(15,2) NOT NULL,
    TIPO_LOCALIZACAO VARCHAR(1) NOT NULL DEFAULT 'U' COMMENT 'U = Urbana, R = Rural',
    ENDERECO VARCHAR(100) NOT NULL,
    NUMERO_ENDERECO VARCHAR(10),
    COMPLEMENTO VARCHAR(100),
    CEP VARCHAR(9),
    BAIRRO VARCHAR(50),
    CIDADE VARCHAR(50) NOT NULL,
    UF VARCHAR(2) NOT NULL,
    PAIS VARCHAR(2) NOT NULL,
    AREA_PRIVATIVA DECIMAL(15,2),
    AREA_CONSTRUIDA DECIMAL(15,2),
    AREA_EXTERNA DECIMAL(15,2),
    AREA_TOTAL DECIMAL(15,2),
    SUITE INT,
    BANHEIRO INT,
    QUARTO INT,
    GARAGEM INT,
    MOBILIADO VARCHAR(1) COMMENT 'S = Semi-Mobiliado, M = Mobiliado, N = Nao-Mobiliado',
    HOSPEDE INT,
    DETALHES TEXT,
    PRIMARY KEY (ID)
);

CREATE TABLE ANUNCIO (
    ID INT NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(150) NOT NULL,
    DATA_INICIO DATE NOT NULL,
    DATA_FIM DATE,
    ATIVO BOOLEAN NOT NULL DEFAULT TRUE,
    ID_ANUNCIANTE INT NOT NULL,
    ID_TIPO_ANUNCIO INT NOT NULL,
    ID_IMOVEL INT NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_ANUNCIO_ANUNCIANTE
        FOREIGN KEY (ID_ANUNCIANTE) REFERENCES ANUNCIANTE (ID),
    CONSTRAINT FK_ANUNCIO_TIPO_ANUNCIO
        FOREIGN KEY (ID_TIPO_ANUNCIO) REFERENCES TIPO_ANUNCIO (ID),
    CONSTRAINT FK_ANUNCIO_IMOVEL
        FOREIGN KEY (ID_IMOVEL) REFERENCES IMOVEL (ID)
);

