-- Garante unicidade de e-mail e CPF/CNPJ do anunciante
ALTER TABLE ANUNCIANTE ADD CONSTRAINT UK_ANUNCIANTE_EMAIL UNIQUE (EMAIL);
ALTER TABLE ANUNCIANTE ADD CONSTRAINT UK_ANUNCIANTE_CPFCNPJ UNIQUE (CPFCNPJ);

-- Tipos de anuncio padrao (Bronze, Prata, Ouro)
INSERT INTO TIPO_ANUNCIO (CATEGORIA, VALOR, DURACAO_DIA) VALUES
    ('B', 50, 15),
    ('P', 100, 30),
    ('O', 200, 60);
