CREATE TABLE IMOVEL_IMAGEM (
    ID INT NOT NULL AUTO_INCREMENT,
    ID_IMOVEL INT NOT NULL,
    NOME_ARQUIVO VARCHAR(255) NOT NULL,
    PRIMARY KEY (ID),
    CONSTRAINT FK_IMAGEM_IMOVEL
        FOREIGN KEY (ID_IMOVEL) REFERENCES IMOVEL (ID)
);
